---
- name: copy over server config
  template:
    src: etc/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload Service | rsyslog

- name: open firewall
  ufw:
    rule: allow
    port: 514
    proto: tcp
